config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  use_doorkeeper

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  concern :commentable do
    resource :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers
  end

  resources :answers, only: [], concerns: :commentable
  root to: "questions#index"

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :body, presence: true

  has_many :answers

  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable

  belongs_to :user

  accepts_nested_attributes_for :attachments

  after_create :update_reputation

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  def index
    @questions = Question.all
    respond_with @questions.to_json(include: :answers)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  # after_action :publish_question, only: [:create]
  before_action :build_answer, only: [:show]

  respond_to :html

  authorize_resource

  def index
    respond_with(@question = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    flash[:notice] = "Your question successfully created." if @question.save
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def load_question
    @question = Question.find_by(id: [params[:id], params[:question_id]])
  end

  # def publish_question
  #   return if @question.errors.any?
  #   ActionCable.server.broadcast(
  #       'questions',
  #       ApplicationController.render(
  #         partial: 'questions/question',
  #         locals: {question: @question}
  #       )
  #   )
  # end

  def question_params
    params.require(:question).permit(:title, :body, attachments_atributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - answer.persisted?
    p= answer.body
    ul
      - answer.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
    - if user_signed_in?
    p= link_to 'Edit', '', class: '.edit-answer-link', data: { answer_id: answer.id}
    p
      = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, "Answer"
        = f.text_area :body
        = f.submit 'Save'

app/views/questions/_form.html.slim
#question_form style="display: none;"
  = form_for @question || :question, remote: true do |f|
    .row
      .input-field.col.s12
        =f.text_field :title
        =f.label :title
    .row
      .input-field.col.s12
        =f.label :body
        =f.text_area :body, class: 'materialize-textarea'
    .row
      .col
        =f.submit "Save", class: 'waves-effect waves-light btn'
      .col
        .btn.cancel-btn.grey.waves-effect.waves-light.lighten-4.black-text Cancel

app/views/questions/_question.html.slim
.collection-item id=dom_id(question)
  = link_to question.title, questions_path

app/views/questions/_question_block.html.slim
.question-info#question_info
  .section
    h5.question-title =@question.title
    p.question-body =@question.body
    / = render 'shared/votes', votable: @question
  .question-controls
    .row
      / - if policy(@question).update?
      /   .col
          = link_to 'Edit', '', class: 'edit-question-link', id: "add_question_btn"
      / - if policy(@question).destroy?
      /   .col
          = link_to 'Delete', @question, method: :delete

= render 'form'

app/views/questions/index.html.slim
- @question.each do |question|
  p= link_to question.title, question

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body, 'Text'
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = a.label :file
      = a.file_field :file

  = f.submit 'Create'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body

- @question.answers.each do |answer|
  p= answer.body

p Attachments:
ul
  - @question.attachments.each do |a|
    li= link_to a.file.identifier, a.file.url

  .comments


= form_for ([@question, @question.answers.build]) do |f|
  p
    = f.label :body, 'Your answer'
    .answer-errors
    = f.text_area :body

  p
    = f.fields_for :attachments, @answer.attachments.build do |a|
      = a.label :file
      = a.file_field :file

  p= f.submit 'Create'